title: Guangyao Meng's Homepage
page-top-title: Guangyao Meng
top-section-bg-text: Intelligence Science and Technology
home-subtitle: Guangyao Meng&ensp;|&ensp;蒙光耀
copyright-text: '&copy; Guangyao Meng 2026-2029. All Rights Reserved.'
